#ifndef CORE_INTERNAL_PLATFORMS_SUPPORT_H_
#define CORE_INTERNAL_PLATFORMS_SUPPORT_H_

#include "../languages/definitions.h"
#include "../languages/support.h"
#include "definitions.h"


// Import language-specific libraries this file will need
/* TODO: Maybe try falling back on <*.h> if <c*> is unfindable?*/
#if COMMON_CURRENT_LANGUAGE == COMMON_LANGUAGE_C
	#include <stdbool.h> // false
#endif

#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#include <threads.h>
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#include <mutex>
	#include <thread>
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#include <pthread.h>
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#include <windows.h>
#else
	// #error "Invalid or unsupported current execution platform."
#endif

// Mutexes

#ifdef COMMON_MUTEX_TYPE
	#undef COMMON_MUTEX_TYPE
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_MUTEX_TYPE mtx_t
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_MUTEX_TYPE COMMON_NAMESPACE_IDENTIFIER(std) mutex
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_TYPE pthread_mutex_t
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_MUTEX_TYPE HANDLE
#endif

#ifdef COMMON_MUTEX_CREATE
	#undef COMMON_MUTEX_CREATE
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_MUTEX_CREATE(MUTEX_OBJECT) mtx_init(&MUTEX_OBJECT, mtx_plain)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_MUTEX_CREATE(MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_CREATE(MUTEX_OBJECT) pthread_mutex_init(&MUTEX_OBJECT, NULL)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_MUTEX_CREATE(MUTEX_OBJECT) MUTEX_OBJECT = CreateMutex(NULL, FALSE, NULL)
#endif

#ifdef COMMON_MUTEX_LOCK
	#undef COMMON_MUTEX_LOCK
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_MUTEX_LOCK(MUTEX_OBJECT) mtx_lock(&MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_MUTEX_LOCK(MUTEX_OBJECT) MUTEX_OBJECT.lock()
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_LOCK(MUTEX_OBJECT) pthread_mutex_lock(&MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	// Do-while usage from Dutchen
	#define COMMON_MUTEX_LOCK(MUTEX_OBJECT) do {} while (WaitForSingleObject(MUTEX_OBJECT, INFINITE) != WAIT_OBJECT_0)
#endif

#ifdef COMMON_MUTEX_UNLOCK
	#undef COMMON_MUTEX_UNLOCK
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_MUTEX_UNLOCK(MUTEX_OBJECT) mtx_unlock(&MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_MUTEX_UNLOCK(MUTEX_OBJECT) MUTEX_OBJECT.unlock()
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_UNLOCK(MUTEX_OBJECT) pthread_mutex_unlock(&MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_MUTEX_UNLOCK(MUTEX_OBJECT) ReleaseMutex(MUTEX_OBJECT)
#endif

// CPU Thread Launching/Joining
// TODO: This is currently broken for COMMON_PLATFORM_WINDOWS.

#ifdef COMMON_CPU_THREAD_TYPE
	#undef COMMON_CPU_THREAD_TYPE
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_CPU_THREAD_TYPE thrd_t
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_CPU_THREAD_TYPE COMMON_NAMESPACE_IDENTIFIER(std) thread
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_CPU_THREAD_TYPE pthread_t
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_CPU_THREAD_TYPE HANDLE
#endif

#ifdef COMMON_CPU_THREAD_LAUNCH
	#undef COMMON_CPU_THREAD_LAUNCH
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_CPU_THREAD_LAUNCH(THREAD_ARRAY, THREAD_COUNT, THREAD_DATA_ARRAY, THREAD_FUNCTION) do { \
		for (int i_ = 0; i_ < THREAD_COUNT; ++i_) { \
			thrd_create(THREAD_ARRAY[i_], THREAD_FUNCTION, &THREAD_DATA_ARRAY[i_]); \
		} \
	} while (false)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_CPU_THREAD_LAUNCH(THREAD_ARRAY, THREAD_COUNT, THREAD_DATA_ARRAY, THREAD_FUNCTION) do { \
		for (int i_ = 0; i_ < THREAD_COUNT; ++i_) { \
			THREAD_ARRAY[i_] = COMMON_NAMESPACE_IDENTIFIER(std) thread(THREAD_FUNCTION, &THREAD_DATA_ARRAY[i_]); \
		} \
	} while (false)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_CPU_THREAD_LAUNCH(THREAD_ARRAY, THREAD_COUNT, THREAD_DATA_ARRAY, THREAD_FUNCTION) do { \
		for (int i_ = 0; i_ < THREAD_COUNT; ++i_) { \
			pthread_create(&THREAD_ARRAY[i_], NULL, THREAD_FUNCTION, &THREAD_DATA_ARRAY[i_]); \
		} \
	} while (false)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_CPU_THREAD_LAUNCH(THREAD_ARRAY, THREAD_COUNT, THREAD_DATA_ARRAY, THREAD_FUNCTION) do { \
		for (int i_ = 0; i_ < THREAD_COUNT; ++i_) { \
			CreateThread(NULL, 0, THREAD_FUNCTION, &THREAD_DATA_ARRAY[i_], 0, THREAD_ARRAY[i_]); \
		} \
	} while (false)
#endif

#ifdef COMMON_CPU_THREAD_JOIN
	#undef COMMON_CPU_THREAD_JOIN
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_CPU_THREAD_JOIN(THREAD_ARRAY, THREAD_COUNT) do { \
		for (int i_ = 0; i_ < THREAD_COUNT; ++i_) { \
			thrd_join(THREAD_ARRAY[i_], NULL); \
		} \
	} while (false)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_CPU_THREAD_JOIN(THREAD_ARRAY, THREAD_COUNT) do { \
		for (int i_ = 0; i_ < THREAD_COUNT; ++i_) { \
			THREAD_ARRAY[i_].join(); \
		} \
	} while (false)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_CPU_THREAD_JOIN(THREAD_ARRAY, THREAD_COUNT) do { \
		for (int i_ = 0; i_ < THREAD_COUNT; ++i_) { \
			pthread_join(THREAD_ARRAY[i_], NULL); \
		} \
	} while (false)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_CPU_THREAD_JOIN(THREAD_ARRAY, THREAD_COUNT) do { \
		WaitForMultipleObjects(THREAD_COUNT, THREAD_ARRAY, TRUE, INFINITE); \
	} while (false)
#endif

// CPU Thread Indices
// TODO: This is currently bugged for COMMON_PLATFORM_WINDOWS.

#ifdef COMMON_CPU_THREAD_INDEX_TYPE
	#undef COMMON_CPU_THREAD_INDEX_TYPE
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB || COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB || COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_CPU_THREAD_INDEX_TYPE int
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_CPU_THREAD_INDEX_TYPE int *
#endif

#ifdef COMMON_CPU_THREAD_INDEX_ACCESS
	#undef COMMON_CPU_THREAD_INDEX_ACCESS
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB || COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB || COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_CPU_THREAD_INDEX_ACCESS(INDEX_ARRAY, POSITION) INDEX_ARRAY[POSITION]
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_CPU_THREAD_INDEX_ACCESS(INDEX_ARRAY, POSITION) *INDEX_ARRAY[POSITION]
#endif

// CPU Thread Function Returns

#ifdef COMMON_CPU_THREAD_FUNCTION_TYPE
	#undef COMMON_CPU_THREAD_FUNCTION_TYPE
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_CPU_THREAD_FUNCTION_TYPE int
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_CPU_THREAD_FUNCTION_TYPE void
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_CPU_THREAD_FUNCTION_TYPE void *
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_CPU_THREAD_FUNCTION_TYPE DWORD WINAPI
#endif

#ifdef COMMON_CPU_THREAD_FUNCTION_RETURN
	#undef COMMON_CPU_THREAD_FUNCTION_RETURN
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_C_STDLIB
	#define COMMON_CPU_THREAD_FUNCTION_RETURN 0
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STDLIB
	#define COMMON_CPU_THREAD_FUNCTION_RETURN
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_CPU_THREAD_FUNCTION_RETURN (NULL)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_CPU_THREAD_FUNCTION_RETURN ((DWORD)0)
#endif

#endif // CORE_INTERNAL_PLATFORMS_SUPPORT_H_
