#ifndef CORE_INTERNAL_PLATFORM_SUPPORT_H
#define CORE_INTERNAL_PLATFORM_SUPPORT_H

#include "language_support.h"

#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STD
	#include <mutex>
	#include <thread>
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#include <pthread.h>
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#include <windows.h>
#else
	// #error "Invalid or unsupported current execution platform."
#endif

// Mutexes

#ifdef COMMON_MUTEX_TYPE
	#undef COMMON_MUTEX_TYPE
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STD
	#define COMMON_MUTEX_TYPE COMMON_STD mutex
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_TYPE pthread_mutex_t
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_MUTEX_TYPE HANDLE
#endif

#ifdef COMMON_MUTEX_CREATE
	#undef COMMON_MUTEX_CREATE
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STD
	#define COMMON_MUTEX_CREATE(MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_CREATE(MUTEX_OBJECT) pthread_mutex_init(&MUTEX_OBJECT, NULL)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_MUTEX_CREATE(MUTEX_OBJECT) MUTEX_OBJECT = CreateMutex(NULL, FALSE, NULL)
#endif

#ifdef COMMON_MUTEX_LOCK
	#undef COMMON_MUTEX_LOCK
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STD
	#define COMMON_MUTEX_LOCK(MUTEX_OBJECT) MUTEX_OBJECT.lock()
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_LOCK(MUTEX_OBJECT) pthread_mutex_lock(&MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	// Do-while usage from Dutchen
	#define COMMON_MUTEX_LOCK(MUTEX_OBJECT) do {} while (WaitForSingleObject(MUTEX_OBJECT, INFINITE) != WAIT_OBJECT_0)
#endif

#ifdef COMMON_MUTEX_UNLOCK
	#undef COMMON_MUTEX_UNLOCK
#endif
#if COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_CPP_STD
	#define COMMON_MUTEX_UNLOCK(MUTEX_OBJECT) MUTEX_OBJECT.unlock()
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_POSIX
	#define COMMON_MUTEX_UNLOCK(MUTEX_OBJECT) pthread_mutex_unlock(&MUTEX_OBJECT)
#elif COMMON_CURRENT_PLATFORM == COMMON_PLATFORM_WINDOWS
	#define COMMON_MUTEX_UNLOCK(MUTEX_OBJECT) ReleaseMutex(MUTEX_OBJECT)
#endif

// TODO: Add support for cross-platform threads

#endif